kind: pipeline
name: default

steps:
- name: plugin
  image: maven:latest
  commands:
  - mvn package
- name: send
  image: plugins/webhook
  settings:
    endpoint: https://tunnel.heinzl.dev
    channel: general
    text: hello