kind: pipeline
name: default

steps:
- name: plugin
  image: maven:latest
  commands:
  - mvn package
- name: send
  image: johnny94/jira-software-cloud-webhook-plugin:latest
  pull: always
  settings:
    url: https://tunnel.heinzl.dev/testbuild
  when:
    status:
    - success
    - failure


