kind: pipeline
name: default

steps:
- name: plugin
  image: maven:latest
  commands:
  - mvn package
- name: send
  image: johnny94/jira-software-cloud-webhook-plugin:latest
  pull: always
  settings:
    url: https://tunnel.heinzl.dev/builddata?baseUrl=https://jheinzl.atlassian.net
    jiraconnectsecret: 
      from_secret: JIRA_CONNECT_SECRET
  when:
    status:
    - success
    - failure
